### ISSUE TITLE
This doesn't work. Documentation is poor

### ISSUE THREAD

**Issue by sdowless** [ZhgChgLi/ZPlayerCacher#1]
I tried implementing this in my project and it doesn't work with iOS 17. 
The documentation on how to implement is also very poor and unclear. 

Please fix

**Comment by zhgchgli0718** [comment]
I have updated the documentation and added a new example project: https://github.com/ZhgChgLi/ZPlayerCacher/tree/main/ZPlayerCacherExample

However, please note that this project is not a complete Project.
The main purpose is to demonstrate the operation mechanism of the Resource Loader; you must understand the basic mechanisms and limitations of the Resource Loader to fully utilize it (e.g., due to an Apple issue, it currently does not support .hls, and your resource files must support HTTP/1.1 Range Requests).
